# Generated by Django 3.0.5 on 2025-04-11 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estimator', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='description',
        ),
        migrations.AddField(
            model_name='project',
            name='completion_percentage',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='project',
            name='estimated_cost',
            field=models.DecimalField(decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='project_type',
            field=models.CharField(choices=[('RES', 'Residential'), ('COM', 'Commercial'), ('REN', 'Renovation')], default='RES', max_length=3),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='project',
            name='location',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='project',
            name='status',
            field=models.CharField(default='In Progress', max_length=20),
        ),
        migrations.AlterField(
            model_name='project',
            name='total_area',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
    ]
