# Generated by Django 3.0.5 on 2025-04-11 19:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('estimator', '0002_auto_20250411_1802'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectEstimate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_name', models.CharField(max_length=255)),
                ('location', models.CharField(max_length=255)),
                ('project_type', models.CharField(max_length=50)),
                ('total_area', models.FloatField()),
                ('length', models.FloatField()),
                ('width', models.FloatField()),
                ('height', models.FloatField()),
                ('floors', models.IntegerField()),
                ('concrete_grade', models.CharField(max_length=50)),
                ('steel_grade', models.CharField(max_length=50)),
                ('brick_type', models.CharField(max_length=50)),
                ('finishing_type', models.CharField(max_length=50)),
                ('labor_hours', models.FloatField()),
                ('skill_level', models.CharField(max_length=50)),
                ('equipment_needs', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.RemoveField(
            model_name='project',
            name='user',
        ),
        migrations.RemoveField(
            model_name='projectlabor',
            name='labor',
        ),
        migrations.RemoveField(
            model_name='projectlabor',
            name='project',
        ),
        migrations.RemoveField(
            model_name='projectmaterial',
            name='material',
        ),
        migrations.RemoveField(
            model_name='projectmaterial',
            name='project',
        ),
        migrations.DeleteModel(
            name='CostEstimate',
        ),
        migrations.DeleteModel(
            name='Labor',
        ),
        migrations.DeleteModel(
            name='Material',
        ),
        migrations.DeleteModel(
            name='Project',
        ),
        migrations.DeleteModel(
            name='ProjectLabor',
        ),
        migrations.DeleteModel(
            name='ProjectMaterial',
        ),
    ]
